"use client";

export default function TermsPage() {
  const sections = [
    {
      title: "Acceptance of Terms",
      content:
        "By accessing or using The Prism platform, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use the platform. These terms apply to all visitors, users, and others who access or use the service. Continued use of the platform following any changes constitutes acceptance of those changes.",
    },
    {
      title: "Description of Service",
      content:
        "The Prism provides a narrative intelligence platform that aggregates, analyzes, and presents news articles and information from various sources. The platform includes bias analysis, AI-powered chat, personalized feeds, and data visualization tools. We reserve the right to modify, suspend, or discontinue any aspect of the service at any time without prior notice. The service is provided on an 'as is' and 'as available' basis.",
    },
    {
      title: "User Accounts",
      content:
        "You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate, current, and complete information during the registration process. You must notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these terms or engage in abusive behavior. Account sharing is prohibited.",
    },
    {
      title: "Acceptable Use",
      content:
        "You agree to use The Prism only for lawful purposes and in accordance with these terms. You may not use the platform to impersonate others, distribute malware, attempt to gain unauthorized access to our systems, scrape or harvest data without permission, or engage in any activity that disrupts or interferes with the platform. Automated access via bots or scripts is prohibited without explicit written consent.",
    },
    {
      title: "Intellectual Property",
      content:
        "The Prism platform, including its code, design, logos, and original content, is owned by The Prism and protected by intellectual property laws. Our name, logo, and brand elements may not be used without permission. User-generated content remains the property of its creator, but by posting it on the platform, you grant us a license to display and distribute it within the service. The analysis and insights generated by our AI systems are provided as informational tools and do not constitute professional advice.",
    },
    {
      title: "Content & Data Accuracy",
      content:
        "News articles and information displayed on The Prism are sourced from third-party publishers. We do not guarantee the accuracy, completeness, or timeliness of third-party content. Bias analysis scores and AI-generated insights are estimates based on algorithmic processing and should not be considered definitive. Users should verify critical information from primary sources. We are not responsible for decisions made based on platform content.",
    },
    {
      title: "Privacy & Data Protection",
      content:
        "Your use of The Prism is also governed by our Privacy Policy, which explains how we collect, use, and protect your personal data. By using the platform, you consent to the data practices described in the Privacy Policy. You are responsible for ensuring that any data you submit complies with applicable privacy laws. We implement security measures to protect your data but cannot guarantee absolute security.",
    },
    {
      title: "Third-Party Links & Services",
      content:
        "The Prism may contain links to third-party websites, articles, and services. We do not endorse or assume responsibility for the content, privacy policies, or practices of any third-party services. Your interactions with third parties are solely between you and them. We recommend reviewing the terms and policies of any third-party services you access through our platform.",
    },
    {
      title: "Limitation of Liability",
      content:
        "To the maximum extent permitted by law, The Prism and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform. This includes, but is not limited to, loss of data, revenue, or profits. Our total liability for any claims related to the service shall not exceed the amount you have paid us in the twelve months preceding the claim. Some jurisdictions do not allow certain limitations of liability, so these limitations may not apply to you.",
    },
    {
      title: "Termination",
      content:
        "We may terminate or suspend your account and access to the platform at any time, without prior notice, for conduct that we believe violates these terms or is harmful to the platform, its users, or third parties. Upon termination, your right to use the platform will immediately cease. Sections relating to intellectual property, limitation of liability, and dispute resolution shall survive termination.",
    },
    {
      title: "Changes to Terms",
      content:
        "We reserve the right to modify these terms at any time. We will notify users of material changes via email or through platform notifications. Your continued use of The Prism after changes take effect constitutes your acceptance of the new terms. If you do not agree with the modified terms, you must stop using the platform. It is your responsibility to review these terms periodically.",
    },
    {
      title: "Governing Law",
      content:
        "These terms shall be governed by and construed in accordance with the laws of the jurisdiction in which The Prism operates, without regard to its conflict of law provisions. Any disputes arising from these terms or your use of the platform shall be resolved through binding arbitration or in the competent courts of that jurisdiction. You waive the right to participate in class action lawsuits against The Prism.",
    },
    {
      title: "Contact Information",
      content:
        "For questions about these terms, please contact us at legal@theprism.io. You may also reach us by mail at the registered address of The Prism. We aim to respond to all legal inquiries within 14 business days. For urgent matters regarding terms violations or abuse reports, please use the report feature within the platform.",
    },
  ];

  return (
    <div
      className="relative min-h-screen overflow-hidden"
      style={{
        background: "var(--background)",
        color: "var(--text-primary)",
      }}
    >
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(circle at top, var(--primary-soft), transparent 35%)",
        }}
      />
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(circle at bottom right, var(--secondary-soft), transparent 30%)",
        }}
      />

      <main className="relative z-10 mx-auto max-w-4xl px-6 py-16 md:px-10 md:py-24">
        <div className="mb-14">
          <p className="mb-3 text-[11px] font-black tracking-[0.3em] text-[var(--primary)] uppercase">
            Legal
          </p>
          <h1 className="text-4xl font-black uppercase tracking-tight md:text-5xl">
            Terms & Conditions
          </h1>
          <p className="mt-4 text-sm text-[var(--text-muted)]">
            Last updated: July 1, 2026
          </p>
          <p className="mt-6 max-w-2xl text-[15px] leading-relaxed text-[var(--text-secondary)]">
            These Terms and Conditions govern your use of The Prism narrative
            intelligence platform. By accessing or using our service, you agree
            to comply with and be bound by these terms. Please read them
            carefully.
          </p>
        </div>

        <div className="space-y-10">
          {sections.map((section, i) => (
            <section
              key={i}
              className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 md:p-8"
            >
              <div className="mb-3 flex items-center gap-3">
                <span className="flex h-7 w-7 items-center justify-center rounded-lg border border-[var(--primary-border)] bg-[var(--primary-soft)] text-[11px] font-black text-[var(--primary)]">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <h2 className="text-lg font-black uppercase tracking-[0.05em]">
                  {section.title}
                </h2>
              </div>
              <p className="text-[15px] leading-relaxed text-[var(--text-secondary)]">
                {section.content}
              </p>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
