"use client";

export default function AIDisclosurePage() {
  const sections = [
    {
      title: "How We Use AI",
      content:
        "The Prism uses artificial intelligence and machine learning technologies to analyze, organize, summarize, and present information. AI systems may assist with news analysis, narrative detection, bias analysis, personalized recommendations, search, and conversational features. AI is used as a tool to help users explore information more efficiently and does not replace human judgment.",
    },
    {
      title: "AI-Generated Content",
      content:
        "Some content, summaries, explanations, classifications, recommendations, and insights presented on The Prism may be generated or assisted by AI. AI-generated content may contain errors, omissions, outdated information, or inaccurate interpretations. Content generated by AI should be treated as informational and should not be assumed to be factual or authoritative without independent verification.",
    },
    {
      title: "Bias Analysis",
      content:
        "The Prism may use AI and algorithmic systems to estimate potential bias, framing, sentiment, narrative patterns, and differences in coverage across news sources. These assessments are based on statistical and computational models and represent estimates rather than objective determinations of truth or bias. Different models, sources, or methodologies may produce different results.",
    },
    {
      title: "AI Chat & Assistants",
      content:
        "The Prism may provide AI-powered conversational features that allow users to ask questions, explore news, summarize information, or analyze topics. Responses are generated automatically and may occasionally be incorrect, incomplete, misleading, or inappropriate. Users should independently verify important claims and should not rely on AI responses as professional, legal, financial, medical, or other specialized advice.",
    },
    {
      title: "Third-Party AI Services",
      content:
        "Some AI functionality may be provided through third-party artificial intelligence models, APIs, infrastructure, or service providers. Depending on the feature and applicable configuration, information submitted to an AI-powered feature may be processed by these providers to deliver the requested functionality. We take reasonable steps to select and configure third-party services appropriately, but their processing may also be subject to their own terms and privacy policies.",
    },
    {
      title: "Training & Model Improvement",
      content:
        "We may use interactions, feedback, technical information, or other permitted data to evaluate, improve, and maintain our AI-powered features, subject to our Privacy Policy and applicable law. Where third-party AI providers are used, their handling of data is governed by the applicable agreements, configurations, and policies. We do not represent that every interaction with an AI feature will be excluded from all forms of model improvement unless expressly stated.",
    },
    {
      title: "Human Oversight",
      content:
        "AI systems used by The Prism operate with varying degrees of automated processing. While we may use human review, testing, monitoring, and quality controls to evaluate our AI systems, not every AI-generated output is reviewed by a person before it is presented to users. Automated outputs should therefore be evaluated with appropriate caution.",
    },
    {
      title: "Accuracy & Limitations",
      content:
        "Artificial intelligence systems can produce plausible-sounding information that is inaccurate or unsupported. AI systems may also misunderstand context, fail to recognize sarcasm or nuance, reproduce errors present in source material, or generate inconsistent conclusions. The Prism does not guarantee that AI-generated outputs are accurate, complete, unbiased, current, or suitable for any particular purpose.",
    },
    {
      title: "User Responsibility",
      content:
        "Users are responsible for evaluating AI-generated information before relying on it or sharing it with others. You should consult authoritative primary sources when accuracy is important and seek qualified professional advice when appropriate. You should not use The Prism's AI features as the sole basis for decisions that could result in financial, legal, medical, professional, or other significant consequences.",
    },
    {
      title: "Privacy & Sensitive Information",
      content:
        "Users should avoid submitting passwords, authentication credentials, highly sensitive personal information, confidential business information, or other information they are not authorized to share through AI-powered features. Our collection and use of information is described in our Privacy Policy. AI processing may require information to be transmitted to systems operated by us or our service providers.",
    },
    {
      title: "Changes to AI Features",
      content:
        "AI technologies and the features available through The Prism may change over time. We may introduce new models, modify existing systems, change third-party providers, or discontinue AI-powered functionality. These changes may affect the behavior, capabilities, and outputs of our AI features. We may update this disclosure as our use of artificial intelligence evolves.",
    },
    {
      title: "No Guarantee of Neutrality",
      content:
        "The Prism is designed to help users identify and explore different narratives, perspectives, and patterns in news coverage. However, the use of AI does not guarantee neutrality or eliminate bias. AI systems can reflect limitations or biases present in their training data, source material, algorithms, prompts, or design. Our AI outputs should therefore be understood as analytical tools rather than definitive judgments.",
    },
  ];

  return (
    <div
      className="relative min-h-screen overflow-hidden"
      style={{
        background: "var(--background)",
        color: "var(--text-primary)",
      }}
    >
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(circle at top, var(--primary-soft), transparent 35%)",
        }}
      />
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(circle at bottom right, var(--secondary-soft), transparent 30%)",
        }}
      />

      <main className="relative z-10 mx-auto max-w-4xl px-6 py-16 md:px-10 md:py-24">
        <div className="mb-14">
          <p className="mb-3 text-[11px] font-black tracking-[0.3em] text-[var(--primary)] uppercase">
            Transparency
          </p>

          <h1 className="text-4xl font-black uppercase tracking-tight md:text-5xl">
            AI Disclosure
          </h1>

          <p className="mt-4 text-sm text-[var(--text-muted)]">
            Last updated: July 1, 2026
          </p>

          <p className="mt-6 max-w-2xl text-[15px] leading-relaxed text-[var(--text-secondary)]">
            The Prism uses artificial intelligence to help analyze and
            understand news and information. This disclosure explains how AI is
            used across the platform, its limitations, and what users should
            consider when interacting with AI-powered features.
          </p>
        </div>

        <div className="space-y-10">
          {sections.map((section, i) => (
            <section
              key={i}
              className="rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 md:p-8"
            >
              <div className="mb-3 flex items-center gap-3">
                <span className="flex h-7 w-7 items-center justify-center rounded-lg border border-[var(--primary-border)] bg-[var(--primary-soft)] text-[11px] font-black text-[var(--primary)]">
                  {String(i + 1).padStart(2, "0")}
                </span>

                <h2 className="text-lg font-black uppercase tracking-[0.05em]">
                  {section.title}
                </h2>
              </div>

              <p className="text-[15px] leading-relaxed text-[var(--text-secondary)]">
                {section.content}
              </p>
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
